<?php
/**
 * Registers Evently's 14 block patterns (brief §25). Each pattern's content
 * is generated by capturing the SAME template-parts the live homepage uses
 * (see evently_capture_template_part()) — never a hand-duplicated copy, so
 * a pattern inserted into any page always matches the theme's real design
 * and, where the section is adapter-backed, real data.
 *
 * Pattern content lives one function per file under patterns/, matching
 * the brief's file tree; this file only wires them into
 * register_block_pattern().
 *
 * @package Evently
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

foreach (
	array(
		'hero.php',
		'event-search.php',
		'event-grid.php',
		'event-carousel.php',
		'categories.php',
		'featured-event.php',
		'nearby-events.php',
		'calendar.php',
		'how-it-works.php',
		'ticket-preview.php',
		'organizer.php',
		'testimonials.php',
		'blog.php',
		'final-cta.php',
	) as $evently_pattern_file
) {
	$evently_pattern_path = EVENTLY_DIR . 'patterns/' . $evently_pattern_file;
	if ( is_readable( $evently_pattern_path ) ) {
		require_once $evently_pattern_path;
	}
}
unset( $evently_pattern_file, $evently_pattern_path );

/**
 * Registry: pattern slug => [title, content-generator function, categories, viewportWidth].
 *
 * @return array
 */
function evently_get_pattern_registry() {
	return array(
		'hero'            => array( __( 'Evently Hero', 'evently' ), 'evently_pattern_content_hero' ),
		'event-search'    => array( __( 'Evently Event Search', 'evently' ), 'evently_pattern_content_event_search' ),
		'event-grid'      => array( __( 'Evently Event Grid', 'evently' ), 'evently_pattern_content_event_grid' ),
		'event-carousel'  => array( __( 'Evently Event Carousel', 'evently' ), 'evently_pattern_content_event_carousel' ),
		'categories'      => array( __( 'Evently Categories', 'evently' ), 'evently_pattern_content_categories' ),
		'featured-event'  => array( __( 'Evently Featured Event', 'evently' ), 'evently_pattern_content_featured_event' ),
		'nearby-events'   => array( __( 'Evently Nearby Events', 'evently' ), 'evently_pattern_content_nearby_events' ),
		'event-calendar'  => array( __( 'Evently Event Calendar', 'evently' ), 'evently_pattern_content_calendar' ),
		'how-it-works'    => array( __( 'Evently How It Works', 'evently' ), 'evently_pattern_content_how_it_works' ),
		'ticket-preview'  => array( __( 'Evently Ticket Preview', 'evently' ), 'evently_pattern_content_ticket_preview' ),
		'organizer-cta'   => array( __( 'Evently Organizer CTA', 'evently' ), 'evently_pattern_content_organizer' ),
		'testimonials'    => array( __( 'Evently Testimonials', 'evently' ), 'evently_pattern_content_testimonials' ),
		'blog-grid'       => array( __( 'Evently Blog Grid', 'evently' ), 'evently_pattern_content_blog' ),
		'cta'             => array( __( 'Evently CTA', 'evently' ), 'evently_pattern_content_final_cta' ),
	);
}

/**
 * Register every pattern in the registry whose content function exists.
 *
 * @return void
 */
function evently_register_patterns() {
	foreach ( evently_get_pattern_registry() as $evently_slug => $evently_pattern ) {
		list( $evently_title, $evently_content_fn ) = $evently_pattern;

		if ( ! function_exists( $evently_content_fn ) ) {
			continue;
		}

		$evently_content = call_user_func( $evently_content_fn );
		if ( '' === trim( (string) $evently_content ) ) {
			continue;
		}

		register_block_pattern(
			'evently/' . $evently_slug,
			array(
				'title'         => $evently_title,
				'categories'    => array( 'evently' ),
				'content'       => $evently_content,
				'viewportWidth' => 1400,
			)
		);
	}
}
add_action( 'init', 'evently_register_patterns', 20 ); // After post types/taxonomies (priority 10) are registered.
